* Add support for removal of previously installed drivers.

diff --git a/configure-ndiswrapper b/configure-ndiswrapper
--- a/configure-ndiswrapper
+++ b/configure-ndiswrapper
@@ -21,46 +21,51 @@ error() {
 			echo ""
 			echo "Aborting."
 			echo ""
-			exit 2
+			exit 1
 			;;
 		root)
 			ETIT="must be root!"
 			EMSG="You must be root to use this program, aborting."
-			ERET=3
+			ERET=2
 			;;
 		ndis)
 			ETIT="ndiswrapper not found!"
 			EMSG="The 'ndiswrapper' command was not found in PATH, aborting."
-			ERET=4
+			ERET=3
 			;;
 		kmod)
 			ETIT="ndiswrapper module not installed"
 			EMSG="The 'ndiswrapper' kernel module is not installed, aborting."
-			ERET=5
+			ERET=4
 			;;
 		driv)
 			ETIT="driver installation failed"
 			EMSG="Failed to install a ndis driver, aborting."
-			ERET=6
+			ERET=5
 			;;
 		regx)
 			ETIT="regexp error"
 			EMSG="Unable to determine ndis driver name with regular expression"
-			ERET=7
+			ERET=6
 			;;
 		nodo)
 			ETIT="driver already installed"
 			EMSG="The driver you chose is already installed, aborting."
-			ERET=8
+			ERET=7
 			;;
 		undo)
-			ETIT="ndiswrapper failure"
+			ETIT="ndiswrapper failed"
 			EMSG="ndiswrapper failed to remove driver that failed installation, aborting."
+			ERET=8
+			;;
+		used)
+			ETIT="ndiswrapper in use"
+			EMSG="The ndiswrapper kernel module is already being used, aborting."
 			ERET=9
 			;;
 		abort)
-			ETIT="aborted installation"
-			EMSG="Aborting ndiswrapper installation"
+			ETIT="aborting configuration"
+			EMSG="Aborting ndiswrapper configuration"
 			ERET=255
 			;;
 	esac
@@ -105,9 +110,41 @@ modprobe -q -i ndiswrapper 2>/dev/null	|| error "kmod"
 
 ###---------------------------------------------------------------###
 
-ssft_display_message "Usage" "$(usage)"
-
 while true; do
+	NDIS_INSTALLED_DRIVERS=( $(ndiswrapper -l | awk '/^.+[ \t]*:.*/{ print $1 }') )
+
+	if [[ ${NDIS_INSTALLED_DRIVERS[@]} ]]; then
+		while [[ ${#NDIS_INSTALLED_DRIVERS[@]} -gt 0 ]]; do
+			if ssft_select_single "Install or Remove" \
+				"Would you like to install or remove ndiswrapper drivers?" \
+				"Install" "Remove"; then
+				case "${SSFT_RESULT}" in
+					Install)
+						break
+						;;
+					Remove)
+						if ssft_select_multiple "Select drivers" \
+							"Select the drivers you would like to remove." \
+							${NDIS_INSTALLED_DRIVERS[@]}; then
+							if [[ ${SSFT_RESULT} ]]; then
+								for driver in ${SSFT_RESULT}; do
+									ndiswrapper -r "${driver}" || error "undo"
+								done
+							fi
+						else
+							error "abort"
+						fi
+						continue 2
+						;;
+				esac
+			else
+				error "abort"
+			fi
+		done
+	fi
+
+	ssft_display_message "Usage" "$(usage)"
+
 	unset NDIS_DRIVER
 
 	if ssft_file_selection "Select driver" "Select Windows .inf driver to install."; then
@@ -130,10 +167,11 @@ while true; do
 	[[ ${NDIS_DRIVER} =~ '^(.*/)?(.+)\.[Ii][Nn][Ff]$' ]] || error "regx"
 	NDIS_DRIVER_NAME=$(tr 'A-Z' 'a-z' <<< ${BASH_REMATCH[2]})
 
-	[[ -d "/etc/ndiswrapper/${NDIS_DRIVER_NAME}" ]] && error "nodo"
+	[[ " ${NDIS_INSTALLED_DRIVERS[@]} " == *" ${NDIS_DRIVER_NAME} "* ]] && error "nodo"
 
 	NDIS_INSTALL_RESULT=$(ndiswrapper -i ${NDIS_DRIVER} 2>&1)
 	if [[ ${?} -eq 0 ]]; then
+		lsmod | grep -q -w ndiswrapper && error "used"
 		NDIS_MODPROBE_RESULT=$(modprobe ndiswrapper 2>&1)
 		if [[ ${?} -eq 0 ]]; then
 			ssft_display_message "ndiswrapper installed" \
